apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: data01
 labels:
   billingType: hourly
   region: eu-gb
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 20MB
 storageClassName: ibmc-file-silver