apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
  template:
    spec:
      containers:
      - name: es-container
        image: elasticsearch:7.9.1