apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: es01
  name: es01
spec:
  selector:
    matchLabels:
      io.kompose.service: es01
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: es01
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xms1024m -Xmx1024m
        - name: bootstrap.memory_lock
          value: "true"
        - name: cluster.name
          value: es-docker-cluster
        - name: discovery.type
          value: single-node
        - name: node.name
          value: es01
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
        name: es01
        ports:
        - containerPort: 9200
        resources: {}
      restartPolicy: Always
status: {}
